Bump black to 22.3.0 and run it on all files
This fixes the problem:
```
ImportError: cannot import name '_unicodefun' from
'click' ([...]/lib/python3.7/site-packages/click/__init__.py)
```

This commit also make some format changes, which are required to make
our CI pipeline happy again.

All files were formatted by running:
```
pre-commit run --all-files
```